// <auto-generated />
using System;
using DomusFi.Infra.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomusFi.Infra.Data.Migrations
{
    [DbContext(typeof(DomusFiDbContext))]
    [Migration("20260725025859_banco-inicial")]
    partial class bancoinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomusFi.Domain.Models.Pessoas", b =>
                {
                    b.Property<Guid>("IdPessoas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPessoas");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("DomusFi.Domain.Models.TipoDespesa", b =>
                {
                    b.Property<Guid>("IdTipoDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDespesa");

                    b.ToTable("TipoDespesa");
                });

            modelBuilder.Entity("DomusFi.Domain.Models.Transacoes", b =>
                {
                    b.Property<Guid>("IdTransacoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdPessoa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoDespesa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTransacoes");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("IdTipoDespesa");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("DomusFi.Domain.Models.Transacoes", b =>
                {
                    b.HasOne("DomusFi.Domain.Models.Pessoas", "Pessoas")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomusFi.Domain.Models.TipoDespesa", "TipoDespesa")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdTipoDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoas");

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("DomusFi.Domain.Models.Pessoas", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("DomusFi.Domain.Models.TipoDespesa", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
